chakra:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project:  "{{ env_var('GCP_PROJECT') }}"
      dataset:  "{{ env_var('BQ_DATASET', 'chakra_raw') }}"
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      threads: 4
      timeout_seconds: 300
